# To create a custom ONNX model, you can follow the online documentation: https://www.stereolabs.com/docs/yolo/export

/**:
  ros__parameters:
      object_detection:
          custom_onnx_file: '/home/alec/ros_ws/src/mhsboat_ctrl/best.onnx' # Path to the YOLO-like ONNX file for custom object detection directly performed by the ZED SDK
          custom_onnx_input_size: 512 # Resolution used with the YOLO-like ONNX file. For example, 512 means a input tensor '1x3x512x512' 
          
          custom_class_count: 24 # Number of classes in the custom ONNX file. For example, 80 for YOLOv8 trained on COCO dataset

          # TODO: Add one instance of each class to the list below
          # Note: create a class_XXX identifier for each class in the custom ONNX file.
          # Note: XXX is a number from 000 to 'custom_class_count-1', and it must be unique for each class.
          # Note: the class_XXX identifier is not required to match the class ID [model_class_id] in the custom ONNX file.

          class_000:
            label: 'black_buoy'
            model_class_id: 0 # Class ID of the object in the custom ONNX file (it is not required that this value matches the value in the 'class_XXX' identifier)
            enabled: true # Enable/disable the detection of this class
            confidence_threshold: 50.0 # Minimum value of the detection confidence of an object [0,99]
            is_grounded: true # Provide hypothesis about the object movements (degrees of freedom or DoF) to improve the object tracking
            is_static: false # Provide hypothesis about the object staticity to improve the object tracking
            tracking_timeout: -1.0 # Maximum tracking time threshold (in seconds) before dropping the tracked object when unseen for this amount of time
            tracking_max_dist: -1.0 # Maximum tracking distance threshold (in meters) before dropping the tracked object when unseen for this amount of meters. Only valid for static object
            max_box_width_normalized: -1.0 # Maximum allowed width normalized to the image size
            min_box_width_normalized: -1.0 # Minimum allowed width normalized to the image size
            max_box_height_normalized: -1.0 # Maximum allowed height normalized to the image size
            min_box_height_normalized: -1.0 # Minimum allowed height normalized to the image size
            max_box_width_meters: -1.0 # Maximum allowed 3D width
            min_box_width_meters: -1.0 # Minimum allowed 3D width
            max_box_height_meters: -1.0 # Maximum allowed 3D height
            min_box_height_meters: -1.0 # Minimum allowed 3D height
            object_acceleration_preset: 'DEFAULT' # Object acceleration preset. Possible values: 'DEFAULT', 'LOW', 'MEDIUM', 'HIGH'
            max_allowed_acceleration: 100000.0 # If set with a different value from the default [100000], this value takes precedence over the selected preset, allowing for a custom maximum acceleration. Unit is m/s^2.
            
          class_001:
            label: 'black_circle'
            model_class_id: 1
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_002:
            label: 'black_cross'
            model_class_id: 2
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_003:
            label: 'black_triangle'
            model_class_id: 3
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_004:
            label: 'blue_buoy'
            model_class_id: 4
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_005:
            label: 'blue_circle'
            model_class_id: 5
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_006:
            label: 'blue_cross'
            model_class_id: 6
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_007:
            label: 'blue_racquet_ball'
            model_class_id: 7
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_008:
            label: 'blue_triangle'
            model_class_id: 8
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_009:
            label: 'dock'
            model_class_id: 9
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_010:
            label: 'green_buoy'
            model_class_id: 10
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_011:
            label: 'green_circle'
            model_class_id: 11
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_012:
            label: 'green_cross'
            model_class_id: 12
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_013:
            label: 'green_pole_buoy'
            model_class_id: 13
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_014:
            label: 'green_triangle'
            model_class_id: 14
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_015:
            label: 'red_buoy'
            model_class_id: 15
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_016:
            label: 'red_circle'
            model_class_id: 16
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_017:
            label: 'red_cross'
            model_class_id: 17
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_018:
            label: 'red_pole_buoy'
            model_class_id: 18
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_019:
            label: 'red_racquet_ball'
            model_class_id: 19
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_020:
            label: 'red_square'
            model_class_id: 20
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_021:
            label: 'yellow_buoy'
            model_class_id: 21
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_022:
            label: 'yellow_racquet_ball'
            model_class_id: 22
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0

          class_023:
            label: 'unknown'
            model_class_id: 23
            enabled: true
            confidence_threshold: 50.0
            is_grounded: true
            is_static: false
            tracking_timeout: -1.0
            tracking_max_dist: -1.0
            max_box_width_normalized: -1.0
            min_box_width_normalized: -1.0
            max_box_height_normalized: -1.0
            min_box_height_normalized: -1.0
            max_box_width_meters: -1.0
            min_box_width_meters: -1.0
            max_box_height_meters: -1.0
            min_box_height_meters: -1.0
            object_acceleration_preset: 'DEFAULT'
            max_allowed_acceleration: 100000.0