ekf_localization:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.2
    two_d_mode: false
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    transform_time_offset: 0.1

    odom0: /odom
    odom0_differential: false
    odom0_relative: false

    imu0: /imu/data
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false]
    imu0_differential: false
    imu0_relative: false
